# Generated by Django 2.1.7 on 2019-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0002_auto_20190221_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='asign',
            field=models.BooleanField(default=False),
        ),
    ]
