# Generated by Django 2.1.7 on 2019-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0003_agent_asign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cl',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
