# Generated by Django 2.1.7 on 2019-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0004_auto_20190227_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cl',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
